spring:
  application:
    name: movie-service
  cloud:
    config:
      enabled: false
server:
  port: 8082
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true